# Font Info TOML scaffold for Glyphs
# Fill in the values and paste into the script window.

# General
designer = ""
designerURL = ""
manufacturer = ""
manufacturerURL = ""
copyright = ""
license = ""
licenseURL = ""
trademark = ""
vendorID = ""
